// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg0cDkhzYvW9OXziAcM3y9ChCe8X8Q2iU',
    appId: '1:46889399424:web:cb4b5fe607457783702265',
    messagingSenderId: '46889399424',
    projectId: 'collegeapp-17688',
    authDomain: 'collegeapp-17688.firebaseapp.com',
    storageBucket: 'collegeapp-17688.appspot.com',
    measurementId: 'G-0D185X842M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCktwIJHlJc_4UsKjV_fZY1pt-f_rqjKcs',
    appId: '1:46889399424:android:2994f245bcac216c702265',
    messagingSenderId: '46889399424',
    projectId: 'collegeapp-17688',
    storageBucket: 'collegeapp-17688.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3GxryG4jdVXTjqyNP5xmLwvk63BZZ3RI',
    appId: '1:46889399424:ios:5be4f1dccd895f25702265',
    messagingSenderId: '46889399424',
    projectId: 'collegeapp-17688',
    storageBucket: 'collegeapp-17688.appspot.com',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3GxryG4jdVXTjqyNP5xmLwvk63BZZ3RI',
    appId: '1:46889399424:ios:2e2d627312295680702265',
    messagingSenderId: '46889399424',
    projectId: 'collegeapp-17688',
    storageBucket: 'collegeapp-17688.appspot.com',
    iosBundleId: 'com.example.myApp1.RunnerTests',
  );
}
